// Generated by Haxe 4.3.6
(function ($global) { "use strict";
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var tetris_Main = function() { };
tetris_Main.main = function() {
};
tetris_Main.main();
})({});
